library(gamlss)
library(gamlss.dist)
newage <- seq(35, 85, 0.1)

metrics <- read.csv("gamlss.input.csv",header=FALSE)
m0 <- lms(V2, V1, data=metrics, trans.x=FALSE, method.pb="GAIC", k=5)
pdf(file = "centiles.lms.pdf")
centiles(m0, metrics$V1, cent=c(5,25,50,75,95), legend=FALSE, ylab="Metric", xlab="Age", pch="o", lwd.centiles=c(2.5,2.5,4,2.5,2.5))
dev.off()
mat0 <- centiles.pred(m0, xname="V1", xvalues=newage,type="centiles",cent=c(5,25,50,75,95))
write.csv(mat0, file = "gamlss.predict.csv")

metrics <- read.csv("gamlss.males.input.csv",header=FALSE)
m0 <- lms(V2, V1, data=metrics, trans.x=FALSE, method.pb="GAIC", k=5)
pdf(file = "centiles.lms.males.pdf")
centiles(m0, metrics$V1, cent=c(5,25,50,75,95), legend=FALSE, ylab="Metric", xlab="Age", pch="o", lwd.centiles=c(2.5,2.5,4,2.5,2.5))
dev.off()
mat0 <- centiles.pred(m0, xname="V1", xvalues=newage,type="centiles",cent=c(5,25,50,75,95))
write.csv(mat0, file = "gamlss.predict.males.csv")

metrics <- read.csv("gamlss.females.input.csv",header=FALSE)
m0 <- lms(V2, V1, data=metrics, trans.x=FALSE, method.pb="GAIC", k=5)
pdf(file = "centiles.lms.females.pdf")
centiles(m0, metrics$V1, cent=c(5,25,50,75,95), legend=FALSE, ylab="Metric", xlab="Age", pch="o", lwd.centiles=c(2.5,2.5,4,2.5,2.5))
dev.off()
mat0 <- centiles.pred(m0, xname="V1", xvalues=newage,type="centiles",cent=c(5,25,50,75,95))
write.csv(mat0, file = "gamlss.predict.females.csv")
